# This is a sample user input file.

# The following 8 arguments are required for all configuration files.
data_path: data
molecule: h2o
sim_num: 0
walkers: 5000
timesteps: 20000
start: 5000
stop: 20000

plots:
  - eref
  - one_dist
  - mult_dist
  - two_d_dist


# Additional required argument for one_dist plot: specify which length to analyze.
dist: [0,1]

# Additional required argument for mult_dist and two_d_dist plots: specify which lengths to analyze.
dists: [[0,1], [1,2]]
